var hops = {
    "Admiral": {
        "AA":   14.50,
        "BA":    5.50,
        "loss": 15.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "African Queen": {
        "AA":   15.55,
        "BA":    4.75,
        "sources": [ "Michigan Hop Alliance",
                     "Northern Brewer" ],
        },
    "Agnus": {
        "AA":   11.0,
        "BA":    5.25,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Ahtanum™": {
        "AA":    5.00,
        "BA":    5.38,
        "loss": 48.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Alliance": {
        "AA":    6.15,
        "BA":    3.00,
        "loss": 22.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Altus™": {
        "AA":   16.75,
        "BA":    4.60,
        "sources": [ "BYO Vol. 26 No. 6 Oct. 2020",
                     "Hopsteiner" ],
        },
    "Amallia": {
        "AA":    7.25,
        "BA":    6.25,
        "sources": [ "The Hops List",
                     "Great Lake Hops" ],
        },
    "Amarillo ®": {
        "AA":    9.50,
        "BA":    6.50,
        "loss": 14.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Amethyst": {
        "AA":    4.00,
        "BA":    7.50,
        "sources": [ "The Hops List",
                     "Castle Malting" ],
        },
    "Apollo": {
        "AA":   17.25,
        "BA":    6.75,
        "loss": 15.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Apolon": {
        "AA":   11.00,
        "BA":    4.00,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "Fresh Hops",
                     "Garetz: Using Hops" ],
        },
    "Aquila": {
        "AA":    7.45,
        "BA":    4.40,
        "loss": 60.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Aramis": {
        "AA":    8.10,
        "BA":    4.15,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Archer ®": {
        "AA":    5.00,
        "BA":    2.50,
        "loss": 25.00,
        "sources": [ "British Hop Association",
                     "Charles Faram" ],
        },
    "Ariana": {
        "AA":   11.50,
        "BA":    5.25,
        "sources": [ "BSG Hops",
                     "Crosby Hops" ],
        },
    "Atlas": {
        "AA":   10.00,
        "BA":    4.00,
        "loss": 38.00,
        "sources": [ "The Hops List",
                     "Fresh Hops",
                     "Garetz: Using Hops" ],
        },
    "Aurora": {
        "AA":    8.75,
        "BA":    3.85,
        "loss": 30.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Azacca ®": {
        "AA":   15.00,
        "BA":    4.75,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },

    "Backa": {
        "AA":    4.90,
        "BA":    5.85,
        "loss": 33.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Barbe Rouge": {
        "AA":    7.20,
        "BA":    3.75,
        "loss": 33.00,
        "sources": [ "Michigan Hop Alliance",
                     "Crosby Hops" ],
        },
    "Beata": {
        "AA":    5.25,
        "BA":   10.00,
        "sources": [ "British Hop Association",
                     "Charles Faram" ],
        },
    "Belma ®": {
        "AA":   10.85,
        "BA":    6.00,
        "loss": 15.00,
        "sources": [ "The Hops List",
                     "Hops Direct",
                     "Crosby Hops" ],
        },
    "Bianca": {
        "AA":    7.50,
        "BA":    3.40,
        "sources": [ "The Hops List",
                     "onegreenworld.com" ],
        },
    "Bitter Gold": {
        "AA":   17.10,
        "BA":    7.00,
        "loss": 44.00,
        "sources": [ "The Hops List",
                     "Great Lakes Hops" ],
        },
    "Blato": {
        "AA":    4.50,
        "BA":    3.50,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Blisk": {
        "AA":   11.75,
        "BA":    4.00,
        "loss": 55.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Blue Northern Brewer": {
        "AA":    7.00,
        "BA":    3.50,
        "loss": 22.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Boadicea": {
        "AA":    8.60,
        "BA":    3.70,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Bobek": {
        "AA":    6.00,
        "BA":    5.15,
        "loss": 33.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Bohemie": {
        "AA":    6.50,
        "BA":    7.50,
        "loss": 35.00,
        "sources": [ "John I Haas",
                     "Bohemia Hop A.s." ],
        },
    "Bor (Czech)": {
        "AA":    8.25,
        "BA":    4.88,
        "sources": [ "John I Haas",
                     "Hopsteiner" ],
        },
    "BOR 704 (US)": {
        "AA":    2.50,
        "BA":    3.50,
        "loss": 33.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Bouclier": {
        "AA":    7.55,
        "BA":    2.85,
        "sources": [ "The Hops List",
                     "Charles Faram" ],
        },
    "Bramling": {
        "AA":    5.80,
        "BA":    3.00,
        "loss": 24.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Bramling Cross": {
        "AA":    6.45,
        "BA":    2.63,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Bravo™": {
        "AA":   15.50,
        "BA":    4.00,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Brewer’s Gold (UK)": {
        "AA":    7.30,
        "BA":    3.80,
        "loss": 40.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "Garetz: Using Hops" ],
        },
    "Brewer’s Gold (US)": {
        "AA":    9.80,
        "BA":    4.65,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },
    "BRU-1™": {
        "AA":   14.00,
        "BA":    9.00,
        "sources": [ "John I Haas",
                     "Yakima Valley Hops" ],
        },
    "British Columbia Goldings": {
        "AA":    5.50,
        "BA":    2.50,
        "loss": 22.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Buket": {
        "AA":   11.00,
        "BA":    4.90,
        "loss": 47.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Bullion": {
        "AA":    8.75,
        "BA":    5.95,
        "loss": 55.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },
    "Buzz Bullets": {
        "AA":    9.00,
        "sources": [ "The Hops List",
                     "Yakima Valley Hops" ],
        },

    "Caliente": {
        "AA":   15.45,
        "BA":    4.30,
        "sources": [ "The Hops List",
                     "forum.northernbrewer.com" ],
        },
    "Callista": {
        "AA":    3.70,
        "BA":    6.75,
        "sources": [ "Crosby Hops",
                     "Michigan Hop Alliance" ],
        },
    "Calypso™": {
        "AA":   13.00,
        "BA":    5.50,
        "loss": 33.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Canadian Redvine": {
        "AA":    5.00,
        "BA":    5.50,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Cardinal": {
        "AA":   10.75,
        "BA":    3.90,
        "sources": [ "Michigan Hop Alliance",
                     "Charles Faram" ],
        },
    "Cascade (Argentinia)": {
        "AA":    3.00,
        "BA":    5.75,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "www.thebrewingnetwork.com" ],
        },
    "Cascade (Australia)": {
        "AA":    6.70,
        "BA":    5.88,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "beerco.com.au" ],
        },
    "Cascade (New Zealand)": {
        "AA":    7.00,
        "BA":    5.25,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "Crosby Hops" ],
        },
    "Cascade (UK)": {
        "AA":    6.52,
        "BA":    4.75,
        "loss": 50.00,
        "sources": [ "British Hop Association",
                     "Charles Faram" ],
        },
    "Cascade (US)": {
        "AA":    6.08,
        "BA":    5.75,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Cashmere": {
        "AA":    8.40,
        "BA":    5.20,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "BSG Hops" ],
        },
    "Cekin": {
        "AA":    7.00,
        "BA":    2.50,
        "loss": 21.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Celeia": {
        "AA":    5.15,
        "BA":    3.10,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Centennial": {
        "AA":   10.50,
        "BA":    4.00,
        "loss": 38.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Cerera": {
        "AA":    5.50,
        "BA":    4.15,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Challenger": {
        "AA":    7.55,
        "BA":    3.55,
        "loss": 22.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Chelan": {
        "AA":   13.50,
        "BA":    9.55,
        "loss": 15.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Chinook": {
        "AA":   12.75,
        "BA":    3.50,
        "loss": 31.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Cicero": {
        "AA":    6.50,
        "BA":    2.45,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Citra ®": {
        "AA":   12.15,
        "BA":    3.95,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Cluster (Australia)": {
        "AA":    7.00,
        "BA":    5.00,
        "loss": 17.00,
        "sources": [ "The Hops List",
                     "nationalhomebrew.com.au" ],
        },
    "Cluster (US)": {
        "AA":    7.10,
        "BA":    5.00,
        "loss": 17.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Cobb": {
        "AA":    5.53,
        "BA":    2.38,
        "loss": 54.00,
        "sources": [ "The Hops List",
                     "Willingham Nurseries" ],
        },
    "Columbia": {
        "AA":    7.15,
        "BA":    4.00,
        "loss": 28.00,
        "sources": [ "The Hops List",
                     "Michigan Hop Alliance" ],
        },
    "Columbus": {
        "AA":   16.00,
        "BA":    5.00,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Comet": {
        "AA":   10.75,
        "BA":    4.50,
        "loss": 37.43,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "www.ars.usda.gov/ARSUserFiles/2450/hopcultivars/62013.html",
                     "BSG Hops" ],
        },
    "Contessa™": {
        "AA":    4.00,
        "BA":    6.20,
        "sources": [ "BYO Vol. 26 No. 6 Oct. 2020",
                     "Hopsteiner" ],
        },
    "Crystal": {
        "AA":    4.40,
        "BA":    6.00,
        "loss": 47.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops",
                     "Garetz: Using Hops" ],
        },
    "CTZ": {
        "AA":   15.75,
        "BA":    5.00,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },

    "Dana": {
        "AA":   14.60,
        "BA":    5.00,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Defender": {
        "AA":    4.30,
        "BA":    1.65,
        "loss": 40.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Delta™": {
        "AA":    6.25,
        "BA":    6.25,
        "loss": 15.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Denali™": {
        "AA":   14.25,
        "BA":    4.35,
        "sources": [ "John I Haas",
                     "Michigan Hop Alliance" ],
        },
    "Density": {
        "AA":    5.40,
        "BA":    3.30,
        "loss": 28.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Dragon": {
        "AA":    8.50,
        "BA":    6.00,
        "sources": [ "Michigan Hop Alliance",
                     "Charles Faram" ],
        },
    "Dr. Rudi™": {
        "AA":   10.70,
        "BA":    6.58,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "BSG Hops",
                     "Fresh Hops" ],
        },
    "Dunav": {
        "AA":    7.08,
        "BA":    3.65,
        "loss": 26.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },

    "Early Bird": {
        "AA":    5.55,
        "BA":    2.35,
        "sources": [ "The Hops List",
                     "Willingham Nurseries" ],
        },
    "Early Prolific": {
        "AA":    4.70,
        "BA":    2.20,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Early Promise": {
        "AA":    6.10,
        "BA":    1.70,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "East Kent Goldings": {
        "AA":    5.25,
        "BA":    2.40,
        "loss": 34.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops",
                     "Garetz: Using Hops" ],
        },
    "Eastern Gold": {
        "AA":   12.50,
        "BA":    5.50,
        "loss": 19.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Eastern Green": {
        "AA":    5.15,
        "BA":    1.95,
        "loss": 17.00,
        "sources": [ "The Hops List",
                     "AllGrain.Beer" ],
        },
    "Eastwell Goldings": {
        "AA":    6.00,
        "BA":    3.00,
        "loss": 30.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Ekuanot™ (Equinox)": {
        "AA":   15.00,
        "BA":    5.00,
        "sources": [ "John I Haas",
                     "BSG Hops",
                     "The Hops List" ],
        },
    "El Dorado ®": {
        "AA":   15.00,
        "BA":    7.50,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Elixer": {
        "AA":    6.00,
        "BA":    5.00,
        "sources": [ "BYO Vol. 26 No. 6 Oct. 2020",
                     "Yakima Valley Hops" ],
        },
    "Ella™": {
        "AA":   14.50,
        "BA":    5.85,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Elsaesser": {
        "AA":    4.65,
        "BA":    5.77,
        "loss": 37.00,
        "sources": [ "The Hops List",
                     "AllGrain.Beer" ],
        },
    "Endeavour": {
        "AA":    9.20,
        "BA":    4.48,
        "loss": 20.00,
        "sources": [ "John I Haas",
                     "British Hop Association" ],
        },
    "Enigma™": {
        "AA":   15.50,
        "BA":    5.25,
        "sources": [ "John I Haas",
                     "Crosby Hops" ],
        },
    "Epic": {
        "AA":    4.00,
        "BA":    2.10,
        "sources": [ "British Hop Association",
                     "Charles Faram" ],
        },
    "Ernest": {
        "AA":    5.78,
        "BA":    4.75,
        "sources": [ "British Hop Association",
                     "Charles Faram" ],
        },
    "Eroica": {
        "AA":   12.60,
        "BA":    4.60,
        "loss": 32.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com",
                     "Garetz: Using Hops" ],
        },
    "Eureka™": {
        "AA":   18.50,
        "BA":    5.40,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },

    "Falconer’s Flight ®": {
        "AA":   11.00,
        "BA":    4.42,
        "sources": [ "The Hops List",
                     "Michigan Hop Alliance",
                     "www.winning-homebrew.com" ],
        },
    "First Choice": {
        "AA":    5.70,
        "BA":    5.00,
        "loss": 26.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "First Gold": {
        "AA":    7.30,
        "BA":    3.20,
        "loss": 15.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Flyer": {
        "AA":   10.95,
        "BA":    5.02,
        "sources": [ "British Hop Association",
                     "Charles Faram" ],
        },
    "Fox": {
        "AA":    7.80,
        "BA":    3.25,
        "sources": [ "Michigan Hop Alliance",
                     "Charles Faram" ],
        },
    "Fuggle (UK)": {
        "AA":    4.30,
        "BA":    2.50,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Fuggle (US)": {
        "AA":    4.75,
        "BA":    1.75,
        "loss": 37.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },
    "Furano Ace": {
        "AA":    7.65,
        "BA":    6.30,
        "loss": 30.00,
        "sources": [ "The Hops List",
                     "ars.usda.gov" ],
        },

    "Galaxy™": {
        "AA":   13.75,
        "BA":    6.45,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Galena": {
        "AA":   12.50,
        "BA":    7.75,
        "loss": 18.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops",
                     "Garetz: Using Hops" ],
        },
    "Glacier": {
        "AA":    6.20,
        "BA":    7.75,
        "loss": 27.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Godiva™": {
        "AA":    7.50,
        "BA":    2.45,
        "sources": [ "British Hop Association",
                     "Charles Faram" ],
        },
    "Golden Star": {
        "AA":    5.40,
        "BA":    4.60,
        "loss": 36.00,
        "sources": [ "The Hops List",
                     "AllGrain.Beer" ],
        },
    "Goldings (UK)": {
        "AA":    6.00,
        "BA":    2.95,
        "sources": [ "Charles Faram",
                     "Castle Malting" ],
        },
    "Goldings (US)": {
        "AA":    4.88,
        "BA":    2.50,
        "loss": 33.00,
        "sources": [ "The Hops List",
                     "Hops Direct" ],
        },
    "Green Bullet™": {
        "AA":   12.60,
        "BA":    6.45,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com",
                     "Crosby Hops" ],
        },
    "Groene Bel": {
        "AA":    4.90,
        "BA":    3.50,
        "loss": 42.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },

    "Hallertauer Mittelfrüh": {
        "AA":    3.75,
        "BA":    4.00,
        "loss": 45.00,
        "sources": [ "The Hops List",
                     "BSG Hops" ],
        },
    "Hallertau (US)": {
        "AA":    4.75,
        "BA":    4.50,
        "loss": 45.00,
        "sources": [ "The Hops List",
                     "Hops Direct" ],
        },
    "Hallertau Blanc": {
        "AA":   10.50,
        "BA":    5.10,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Hallertau (NZ)": {
        "AA":    7.25,
        "BA":    7.85,
        "loss": 18.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Hallertau Gold": {
        "AA":    8.50,
        "BA":    6.00,
        "loss": 53.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Harlequin™": {
        "AA":   10.75,
        "BA":    8.00,
        "sources": [ "British Hop Association",
                     "Charles Faram" ],
        },
    "Harmonie": {
        "AA":    6.25,
        "BA":    6.50,
        "loss": 35.00,
        "sources": [ "John I Haas",
                     "Charles Faram" ],
        },
    "Helga": {
        "AA":    6.35,
        "BA":    6.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },
    "Herald": {
        "AA":   12.35,
        "BA":    5.15,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "beerlegends.com" ],
        },
    "Herkules": {
        "AA":   14.50,
        "BA":    4.75,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Hersbrucker": {
        "AA":    3.10,
        "BA":    4.45,
        "loss": 40.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Hersbruker Pure": {
        "AA":    5.35,
        "BA":    2.50,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "beerlegends.com" ],
        },
    "Horizon": {
        "AA":   12.20,
        "BA":    7.30,
        "loss": 18.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Hüll Melon": {
        "AA":    7.30,
        "BA":    7.50,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Hüller Bitterer": {
        "AA":    5.75,
        "BA":    5.00,
        "loss": 40.00,
        "sources": [ "The Hops List",
                     "beerlegends.com" ],
        },

    "Idaho 7™": {
        "AA":   12.75,
        "BA":    5.40,
        "sources": [ "BSG Hops",
                     "Crosby Hops" ],
        },
    "Idaho Gem™": {
        "AA":   12.75,
        "BA":    6.00,
        "loss": 25.00,
        "sources": [ "BSG Hops",
                     "morebeer.com" ],
        },
    "Ivanhoe ®": {
        "AA":    7.70,
        "BA":    4.60,
        "sources": [ "The Hops List",
                     "hopsmeister.com" ],
        },

    "Janus": {
        "AA":    5.10,
        "BA":    2.30,
        "loss": 32.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Jarrylo ®": {
        "AA":   16.00,
        "BA":    6.90,
        "loss": 32.00,
        "sources": [ "Yakima Valley Hops",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Jester ®": {
        "AA":    8.00,
        "BA":    5.00,
        "sources": [ "Crosby Hops",
                     "British Hop Association" ],
        },
    "Junga": {
        "AA":   11.00,
        "BA":    5.00,
        "loss": 32.00,
        "sources": [ "John I Haas",
                     "Michigan Hop Alliance" ],
        },

    "Kazbek": {
        "AA":    6.50,
        "BA":    5.00,
        "sources": [ "John I Haas",
                     "BSG Hops" ],
        },
    "Keyworth’s Early": {
        "AA":    7.78,
        "BA":    3.25,
        "loss": 28.00,
        "sources": [ "The Hops List",
                     "British Hop Association" ],
        },
    "Keyworth’s Midseason": {
        "AA":    7.00,
        "BA":    2.93,
        "loss": 55.00,
        "sources": [ "The Hops List",
                     "British Hop Association" ],
        },
    "Kirin II": {
        "AA":    8.00,
        "BA":    6.40,
        "loss": 30.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Kohatu ®": {
        "AA":    6.75,
        "BA":    5.25,
        "sources": [ "The Hops List",
                     "BSG Hops" ],
        },

    "Landhopfen": {
        "AA":    3.58,
        "BA":    3.10,
        "loss": 34.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Legacy ®": {
        "AA":    7.80,
        "sources": [ "The Hops List",
                     "Hops Direct" ],
        },
    "Lemondrop™": {
        "AA":    6.00,
        "BA":    5.00,
        "sources": [ "Hopsteiner",
                     "John I Haas" ],
        },
    "Liberty": {
        "AA":    4.15,
        "BA":    3.50,
        "loss": 47.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops",
                     "Garetz: Using Hops" ],
        },
    "Limbus":    {
        "AA":    4.78,
        "BA":    3.00,
        "sources": [ "John I Haas",
                     "Brudzynski and Baranowski JIB 2003 p. 154" ],
        },
    "Lomik":    {
        "AA":    4.55,
        "BA":    3.75,
        "sources": [ "John I Haas",
                     "twojbrowar.pl" ],
        },
    "Loral™":    {
        "AA":   11.00,
        "BA":    5.00,
        "loss": 20.00,
        "sources": [ "Yakima Valley Hops",
                     "John I Haas" ],
        },
    "Lotus™":    {
        "AA":   15.00,
        "BA":    5.75,
        "sources": [ "Hopsteiner",
                     "newschoolbeer.com" ],
        },
    "Lubelski": {
        "AA":    4.00,
        "BA":    3.27,
        "loss": 38.00,
        "sources": [ "The Hops List",
                     "Michigan Hop Alliance",
                     "Brudzynski and Baranowski JIB 2003 p. 154",
                     "Charles Faram",
                     "Castle Malting",
                     "Garetz: Using Hops" ],
        },
    "Lublin": {
        "AA":    4.38,
        "BA":    3.25,
        "loss": 50.00,
        "sources": [ "John I Haas",
                     "www.winning-homebrew.com",
                     "Garetz: Using Hops"],
        },
    "Lucan": {
        "AA":    4.00,
        "BA":    3.30,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },

    "Magnat": {
        "AA":   12.60,
        "BA":    3.90,
        "sources": [ "John I Haas",
                     "polishhops.com" ],
        },
    "Magnum (Germany)": {
        "AA":   13.30,
        "BA":    5.60,
        "loss": 17.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Magnum (US)": {
        "AA":   12.88,
        "BA":    5.75,
        "sources": [ "The Hops List",
                     "Hops Direct" ],
        },
    "Mandarina Bavaria": {
        "AA":    8.83,
        "BA":    5.70,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Marco Polo (China)": {
        "AA":   12.55,
        "BA":    5.00,
        "sources": [ "John I Haas",
                     "twojbrowar.com" ],
        },
    "Marynka": {
        "AA":   10.50,
        "BA":   11.60,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Medusa™": {
        "AA":    4.00,
        "BA":    6.15,
        "sources": [ "Michigan Hop Alliance",
                     "Crosby Hops" ],
        },
    "Melba": {
        "AA":    8.50,
        "BA":    3.75,
        "sources": [ "The Hops List",
                     "Hopsteiner" ],
        },
    "Meridian ®": {
        "AA":    6.15,
        "BA":    7.50,
        "sources": [ "Crosby Hops",
                     "www.winning-homebrew.com" ],
        },
    "Merkur": {
        "AA":   13.60,
        "BA":    5.60,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Millennium ®": {
        "AA":   15.50,
        "BA":    4.80,
        "loss": 24.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Minstrel ®": {
        "AA":    6.00,
        "BA":    3.25,
        "sources": [ "British Hop Association",
                     "Charles Faram" ],
        },
    "Mistral": {
        "AA":    9.25,
        "BA":    3.50,
        "sources": [ "Yakima Valley Hops",
                     "Charles Faram" ],
        },
    "Monroe (Germany)": {
        "AA":    2.50,
        "sources": [ "Yakima Valley Hops",
                     "twojbrowar.pl" ],
        },
    "Mosaic ®": {
        "AA":   12.50,
        "BA":    3.50,
        "loss": 15.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Motueka™": {
        "AA":    7.15,
        "BA":    5.25,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Mount Hood": {
        "AA":    5.65,
        "BA":    6.50,
        "loss": 45.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Mount Rainier": {
        "AA":    8.00,
        "BA":    7.25,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },
    "Moutere™": {
        "AA":   18.50,
        "BA":    9.00,
        "loss": 25.00,
        "sources": [ "BSG Hops",
                     "New Zealand Hops",
                     "Charles Farm" ],
        },
    "MultiHead": {
        "AA":    4.58,
        "BA":    6.20,
        "sources": [ "The Hops List",
                     "Great Lake Hops" ],
        },
    "Mystic™": {
        "AA":    5.25,
        "BA":    3.50,
        "sources": [ "British Hop Association",
                     "Charles Faram" ],
        },

    "Nadwislanska": {
        "AA":    4.00,
        "BA":    3.75,
        "loss": 42.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Nelson Sauvin™": {
        "AA":   12.50,
        "BA":    7.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Neo1": {
        "AA":    8.00,
        "BA":    3.15,
        "sources": [ "The Hops List",
                     "allgrain.beer" ],
        },
    "Neoplanta": {
        "AA":    9.30,
        "BA":    4.00,
        "loss": 37.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Newport": {
        "AA":   15.25,
        "BA":    8.20,
        "loss": 40.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Nordgaard": {
        "AA":    7.50,
        "BA":    3.40,
        "loss": 21.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Northdown": {
        "AA":    8.50,
        "BA":    4.60,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Northern Brewer (UK)": {
        "AA":    8.75,
        "BA":    4.00,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Northern Brewer (Ger.)": {
        "AA":    8.25,
        "BA":    4.00,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "BSG Hops",
                     "Garetz: Using Hops" ],
        },
    "Northern Brewer (US)": {
        "AA":    8.75,
        "BA":    4.00,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "Hops Direct",
                     "Garetz: Using Hops" ],
        },
    "Nugget": {
        "AA":   12.40,
        "BA":    4.50,
        "loss": 18.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops",
                     "Garetz: Using Hops" ],
        },

    "Oktawia": {
        "AA":    9.30,
        "BA":    3.75,
        "sources": [ "John I Haas",
                     "Brudzynski and Baranowski JIB 2003 p. 154" ],
        },
    "Olicana ®": {
        "AA":    8.25,
        "BA":    5.00,
        "sources": [ "British Hop Association",
                     "Charles Faram" ],
        },
    "Olympic": {
        "AA":   12.60,
        "BA":    5.25,
        "loss": 40.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Omega": {
        "AA":    9.50,
        "BA":    3.50,
        "loss": 22.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Opal": {
        "AA":   13.50,
        "AA2":   6.50,
        "BA":    4.50,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Orbit": {
        "AA":    5.00,
        "BA":    5.00,
        "sources": [ "The Hops List",
                     "allgrain.beer" ],
        },
    "Orion": {
        "AA":    7.90,
        "BA":    4.50,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },
    "Outeniqua": {
        "AA":   12.75,
        "BA":    4.60,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "beerlegends.com" ],
        },

    "Pacific Gem™": {
        "AA":   14.10,
        "BA":    8.00,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Pacific Jade™": {
        "AA":   13.00,
        "BA":    7.50,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Pacific Sunrise": {
        "AA":   13.50,
        "BA":    6.15,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Pacifica™": {
        "AA":    5.50,
        "BA":    5.85,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Pahto™": {
        "AA":   19.00,
        "BA":    5.12,
        "sources": [ "Yakima Valley Hops",
                     "BSG Hops" ],
        },
    "Palisade ®": {
        "AA":    7.50,
        "BA":    7.00,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Pekko ®": {
        "AA":   14.50,
        "BA":    3.90,
        "sources": [ "John I Haas",
                     "Crosby Hops" ],
        },
    "Perle (Germany)": {
        "AA":    7.00,
        "BA":    5.00,
        "loss": 15.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Perle (US)": {
        "AA":    7.75,
        "BA":    4.00,
        "loss": 17.00,
        "sources": [ "The Hops List",
                     "Hops Direct" ],
        },
    "Phoenix": {
        "AA":   10.50,
        "BA":    4.50,
        "loss": 17.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },
    "Pilgrim": {
        "AA":   11.25,
        "BA":    4.70,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Pilot": {
        "AA":   10.00,
        "BA":    4.15,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Pioneer": {
        "AA":    9.50,
        "BA":    3.90,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Pocket Talisman": {
        "AA":    6.00,
        "BA":    3.20,
        "loss": 30.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Polaris": {
        "AA":   20.60,
        "BA":    5.40,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Precoce de Bourgogne": {
        "AA":    3.40,
        "BA":    3.00,
        "loss": 40.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Premiant (Czech)": {
        "AA":    9.65,
        "BA":    5.50,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Pride of Kent": {
        "AA":    9.50,
        "BA":    7.00,
        "loss": 58.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Pride of Ringwood": {
        "AA":    8.75,
        "BA":    5.50,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },
    "Progress": {
        "AA":    6.60,
        "BA":    2.40,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Pulawski": {
        "AA":    7.05,
        "BA":    3.25,
        "sources": [ "John I Haas",
                     "Michigan Hop Alliance" ],
        },

    "Rakau™": {
        "AA":    9.20,
        "BA":    4.60,
        "loss": 28.00,
        "sources": [ "The Hops List",
                     "BSG Hops" ],
        },
    "Record": {
        "AA":    9.20,
        "BA":    6.30,
        "loss": 42.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Riwaka": {
        "AA":    5.50,
        "BA":    4.75,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Rubin": {
        "AA":   11.25,
        "BA":    4.75,
        "loss": 25.00,
        "sources": [ "John I Haas",
                     "Hop Growers Union of the Czech Republic" ],
        },

    "Saaz (Czech)": {
        "AA":    3.75,
        "BA":    6.10,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Saaz Late (Czech)": {
        "AA":    4.75,
        "BA":    5.25,
        "loss": 50.00,
        "sources": [ "John I Haas",
                     "Bohemia Hop A.s." ],
        },
    "Saaz (US)": {
        "AA":    3.85,
        "BA":    3.75,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "Hops Direct" ],
        },
    "Sabro™": {
        "AA":   14.00,
        "BA":    5.50,
        "sources": [ "Yakima Valley Hops",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Santiam": {
        "AA":    6.40,
        "BA":    7.25,
        "loss": 55.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Saphir": {
        "AA":    3.25,
        "BA":    5.50,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Satus ®": {
        "AA":   13.25,
        "BA":    8.75,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },
    "Saxon": {
        "AA":    9.00,
        "BA":    4.50,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Serebrianka": {
        "AA":    3.50,
        "BA":    3.00,
        "loss": 47.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Shinshuwase": {
        "AA":    6.15,
        "BA":    4.85,
        "loss": 39.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Simcoe ®": {
        "AA":   13.00,
        "BA":    4.50,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Sladek": {
        "AA":    6.65,
        "BA":    7.50,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Smaragd": {
        "AA":    5.00,
        "BA":    4.50,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Smooth Cone": {
        "AA":    8.20,
        "BA":    4.20,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Sonnet": {
        "AA":    4.65,
        "sources": [ "The Hops List",
                     "Castle Malting" ],
        },
    "Sorachi Ace": {
        "AA":   13.15,
        "BA":    6.70,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Southern Aroma": {
        "AA":    4.82,
        "BA":    5.00,
        "sources": [ "Michigan Hop Alliance",
                     "zahops.com" ],
        },
    "Southern Brewer": {
        "AA":    9.90,
        "BA":    4.10,
        "sources": [ "John I Haas",
                     "Fresh Hops" ],
        },
    "Southern Cross™": {
        "AA":   13.00,
        "BA":    6.00,
        "loss": 29.00,
        "sources": [ "The Hops List",
                     "BSG Hops" ],
        },
    "Southern Dawn": {
        "AA":   11.85,
        "BA":    5.10,
        "sources": [ "John I Haas",
                     "Northern Brewer" ],
        },
    "Southern Passion": {
        "AA":   10.05,
        "BA":    7.50,
        "sources": [ "Michigan Hop Alliance",
                     "zahops.com" ],
        },
    "Southern Promise": {
        "AA":   10.50,
        "BA":    4.50,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Southern Star": {
        "AA":   13.40,
        "BA":    5.00,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Sovereign": {
        "AA":    5.75,
        "BA":    2.60,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Spalt": {
        "AA":    4.00,
        "BA":    4.00,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "Garetz: Using Hops" ],
        },
    "Spalter Select": {
        "AA":    4.75,
        "BA":    3.65,
        "loss": 30.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Star": {
        "AA":    3.20,
        "BA":    1.70,
        "loss": 18.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Sterling": {
        "AA":    7.30,
        "BA":    5.00,
        "loss": 30.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Sticklebract": {
        "AA":   11.95,
        "BA":    6.45,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Strata ®": {
        "AA":   11.80,
        "BA":    5.30,
        "sources": [ "Crosby Hops",
                     "Northern Brewer" ],
        },
    "Strisselspalt": {
        "AA":    3.00,
        "BA":    4.35,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Styrian Celeia Goldings": {
        "AA":    4.62,
        "BA":    2.65,
        "sources": [ "homebrewing.org",
                     "Crosby Hops" ],
        },
    "Styrian Gold": {
        "AA":    5.00,
        "BA":    4.75,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Styrian (Savinjski) Golding": {
        "AA":    4.85,
        "BA":    2.75,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Styrian Kolibri": {
        "AA":    5.00,
        "BA":    4.30,
        "sources": [ "Michigan Hop Alliance",
                     "Castle Malting" ],
        },
    "Styrian Wolf": {
        "AA":   13.20,
        "BA":    5.15,
        "sources": [ "Hop Head Farms",
                     "Michigan Hop Alliance" ],
        },
    "Sultana™": {
        "AA":   14.25,
        "BA":    4.35,
        "sources": [ "BYO Vol. 26 No. 6 Oct. 2020: same as Denali",
                     "Hopsteiner" ],
        },
    "Summer": {
        "AA":    6.00,
        "BA":    5.45,
        "sources": [ "The Hops List",
                     "BSG Hops" ],
        },
    "Summit™": {
        "AA":   16.85,
        "BA":    4.60,
        "loss": 15.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Sun": {
        "AA":   14.00,
        "BA":    5.75,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Sunbeam": {
        "AA":    4.50,
        "BA":    2.50,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Sunshine": {
        "AA":    7.48,
        "BA":    2.65,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Super Alpha (Dr. Rudi™)": {
        "AA":   10.70,
        "BA":    6.58,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "BSG Hops",
                     "Fresh Hops" ],
        },
    "Super Galena™": {
        "AA":   14.50,
        "BA":    9.00,
        "loss": 15.00,
        "sources": [ "Hopsteiner",
                     "John I Haas" ],
        },
    "Super Pride": {
        "AA":   14.15,
        "BA":    6.75,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Sussex": {
        "AA":    5.00,
        "BA":    2.80,
        "sources": [ "The Hops List",
                     "British Hop Association" ],
        },
    "Sybilla": {
        "AA":    7.28,
        "BA":    4.00,
        "sources": [ "John I Haas",
                     "Brudzynski and Baranowski JIB 2003 p. 154" ],
        },
    "Sylva": {
        "AA":    6.15,
        "BA":    3.80,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },

    "Taiheke ®": {
        "AA":    6.50,
        "BA":    5.25,
        "sources": [ "Michigan Hop Alliance",
                     "Charles Faram" ],
        },
    "Tahoma": {
        "AA":    7.25,
        "BA":    8.25,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },
    "Talisman": {
        "AA":    6.20,
        "BA":    3.20,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Tardif de Bourgogne": {
        "AA":    4.30,
        "BA":    4.50,
        "loss": 33.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Target": {
        "AA":   10.75,
        "BA":    5.10,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Taurus": {
        "AA":   14.75,
        "BA":    5.00,
        "loss": 30.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Teamaker": {
        "AA":    1.20,
        "BA":    9.30,
        "sources": [ "The Hops List",
                     "Great Lake Hops" ],
        },
    "Tettnanger (Germany)": {
        "AA":    4.05,
        "BA":    4.00,
        "loss": 40.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Tettnanger (Swiss)": {
        "AA":    4.95,
        "BA":    4.68,
        "loss": 43.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Tettnanger (US)": {
        "AA":    4.60,
        "BA":    3.85,
        "loss": 42.00,
        "sources": [ "The Hops List",
                     "BSG Hops" ],
        },
    "Tillicum ®": {
        "AA":   14.50,
        "BA":   10.50,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Tolhurst": {
        "AA":    2.20,
        "BA":    2.90,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Tomahawk ®": {
        "AA":   15.50,
        "BA":    4.62,
        "loss": 50.00,
        "sources": [ "John I Haas",
                     "allgrain.beer" ],
        },
    "Tomyski": {
        "AA":    3.25,
        "BA":    5.50,
        "sources": [ "Wikipedia: Tomyski hops",
                     "revolvy.com" ],
        },
    "Topaz™": {
        "AA":   15.80,
        "BA":    6.90,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Tradition": {
        "AA":    5.55,
        "BA":    4.50,
        "loss": 28.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Triple Pearl": {
        "AA":   10.60,
        "BA":    4.90,
        "sources": [ "Michigan Hop Alliance",
                     "www.winning-homebrew.com" ],
        },
    "Triskel": {
        "AA":    8.50,
        "BA":    4.35,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Triumph": {
        "AA":   10.75,
        "BA":    3.82,
        "sources": [ "BSG Hops",
                     "Great Lake Hops" ],
        },
    "Tsingdao Flower": {
        "AA":    6.75,
        "BA":    3.70,
        "loss": 25.00,
        "sources": [ "John I Haas",
                     "hopofthemonthclub.com" ],
        },

    "Ultra": {
        "AA":    3.40,
        "BA":    4.00,
        "loss": 25.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Universal": {
        "AA":    5.20,
        "BA":    3.70,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },

    "Vanguard": {
        "AA":    5.50,
        "BA":    6.50,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Vic Secret™": {
        "AA":   15.50,
        "BA":    6.95,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Viking": {
        "AA":    9.00,
        "BA":    4.50,
        "loss": 30.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Vital": {
        "AA":   13.00,
        "BA":    9.00,
        "sources": [ "The Hops List",
                     "Charles Faram" ],
        },
    "Vojvodina": {
        "AA":    8.45,
        "BA":    3.55,
        "loss": 24.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },

    "Wai-iti™": {
        "AA":    3.00,
        "BA":    5.00,
        "sources": [ "The Hops List",
                     "BSG Hops" ],
        },
    "Waimea™": {
        "AA":   17.50,
        "BA":    8.00,
        "sources": [ "The Hops List",
                     "BSG Hops" ],
        },
    "Wakatu™": {
        "AA":    7.50,
        "BA":    8.35,
        "sources": [ "The Hops List",
                     "BSG Hops" ],
        },
    "Warrior ®": {
        "AA":   15.80,
        "BA":    5.00,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Whitbread Golding": {
        "AA":    6.35,
        "BA":    2.85,
        "loss": 35.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops" ],
        },
    "Willamette": {
        "AA":    5.00,
        "BA":    3.90,
        "loss": 36.00,
        "sources": [ "The Hops List",
                     "John I Haas",
                     "BSG Hops",
                     "Garetz: Using Hops" ],
        },
    "Willow Creek": {
        "AA":   15.60,
        "BA":    6.70,
        "loss":  0.03,
        "sources": [ "The Hops List",
                     "Farmhouse Brewing Supply" ],
        },
    "Wuerttemberger": {
        "AA":    5.00,
        "BA":    4.00,
        "loss": 28.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },

    "Yakima Cluster": {
        "AA":    7.10,
        "BA":    4.40,
        "loss": 15.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Yakima Gold": {
        "AA":    9.65,
        "BA":    4.65,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },
    "Yeoman": {
        "AA":   14.00,
        "BA":    4.50,
        "loss": 20.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },

    "Zappa™": {
        "AA":    7.00,
        "BA":    8.50,
        "sources": [ "Michigan Hop Alliance",
                     "BSG Hops" ],
        },
    "Zbyszko": {
        "AA":    7.50,
        "BA":    6.35,
        "sources": [ "John I Haas",
                     "Brudzynski and Baranowski JIB 2003 p. 154" ],
        },
    "Zenith": {
        "AA":   10.00,
        "BA":    3.00,
        "loss": 18.00,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Zeus": {
        "AA":   15.75,
        "BA":    5.00,
        "loss": 50.00,
        "sources": [ "The Hops List",
                     "John I Haas" ],
        },
    "Zlatan": {
        "AA":    5.20,
        "BA":    4.30,
        "sources": [ "The Hops List",
                     "Fresh Hops" ],
        },
    "Zula": {
        "AA":   10.75,
        "BA":    5.00,
        "sources": [ "John I Haas",
                     "polishhops.com" ],
        },
    "Zythos ®": {
        "AA":   11.25,
        "BA":    5.45,
        "loss": 30.00,
        "sources": [ "The Hops List",
                     "www.winning-homebrew.com" ],
        },

    }

